import type { Metadata } from "next";
import { Inter as FontSans, Pridi } from "@next/font/google"
import { cn } from "@/lib/utils"



import "./globals.css";

  const pridi = Pridi({
    subsets: ['latin'],
    weight: ['400', '500', '600'], // Escolha os pesos que precisa
  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          pridi
        )}
      >{children}</body>
    </html>
  );
}
